name: Koyeb Hourly Redeploy

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Redeploy Service
        run: |
          curl -sL -o install.sh "https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh"
          bash install.sh
          export PATH="$HOME/.koyeb/bin:$PATH"
          koyeb services redeploy mg-koyebb -a vulnerable-meredithe --use-cache --wait --wait-timeout 3m --token "${{ secrets.KOYEB_API_TOKEN }}"
