name: Koyeb Hourly Redeploy

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Koyeb CLI
        run: |
          wget -q https://github.com/koyeb/koyeb-cli/releases/latest/download/koyeb-cli_linux_amd64.tar.gz
          tar -xzf koyeb-cli_linux_amd64.tar.gz
          sudo mv koyeb /usr/local/bin/
          koyeb version

      - name: Authenticate & Redeploy
        run: |
          koyeb login --token ${{ secrets.KOYEB_API_TOKEN }}
          koyeb services redeploy mg-koyebb -a vulnerable-meredithe --use-cache --wait --wait-timeout 3m
